{
  "language": "java",
  "jdk": "oraclejdk8",
  "jobs": {
    "include": [
      {
        "script": [
          "mvn -DskipMinify=true --projects struts2-jquery-integration-tests -Dmaven.javadoc.skip=true verify"
        ]
      },
      {
        "script": [
          "mvn -DskipMinify=true --projects struts2-jquery-integration-tests -Dmaven.javadoc.skip=true -P phantomjs verify"
        ]
      }
    ]
  },
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}

